export { AboutResponse } from "./about.ts";
export {
  AccountFavoriteItem,
  AccountFavoritesResponse,
  AccountIdentityId,
  AccountSearchResponse,
  LinkIdentityRequest,
  SwitchIdentityRequest,
  UnlinkIdentityRequest,
} from "./accounts.ts";
export {
  ActivityOperation,
  SystemActivityId,
  SystemActivityItem,
  SystemActivityResponse,
  WorkerActivity,
} from "./activity.ts";
export {
  AI_SETTINGS_KEY,
  AiConnectionTestResponse,
  AiProvider,
  AiSettings,
  AiSettingsUpdateRequest,
  AiStatusResponse,
  DEFAULT_AI_MODEL,
  DEFAULT_ORGANIZE_SHARING,
  MAX_ORGANIZE_ITEMS,
  OrganizeProposal,
  OrganizeRequest,
  OrganizeRun,
  OrganizeRunState,
  OrganizeSharing,
  OrganizeSuggestion,
  SystemAiResponse,
} from "./ai.ts";
export { IdentitySummary, LoginRequest, LoginResponse, MeResponse } from "./auth.ts";
export { createBackupClient } from "./backup-client.ts";
export {
  BackupAttachmentInput,
  BackupDestinationInput,
  BackupEstimateJob,
  BackupRecoveryStatus,
  BackupRehearsal,
  BackupRunInput,
  BackupRunSummary,
  BackupSchedule,
  BackupsResponse,
} from "./backups.ts";
export { CanonicalUuid } from "./canonical-uuid.ts";
export type {
  ApiClient,
  ApiClientOptions,
  ApiClientUploadOptions,
  UploadBody,
} from "./client.ts";
export { ApiClientError, buildRequestUrl, createApiClient, toQueryString } from "./client.ts";
export * from "./desktop.ts";
export * from "./desktop-writes.ts";
export { ApiError, ApiErrorKind, statusForKind } from "./error.ts";
export { FsEvent, JobEvent, PingEvent, SseEvent } from "./events.ts";
export {
  FEATURE_IDS,
  FEATURES_SETTINGS_KEY,
  FeatureConfiguration,
  FeatureId,
  FeatureStatus,
  FeaturesUpdateRequest,
  FeatureValues,
  SystemFeaturesResponse,
  WORKER_TOKEN_HEADER,
} from "./features.ts";
export {
  ArchiveEntriesFormat,
  ArchiveEntriesResponse,
  ArchiveEntry,
  CompressRequest,
  CopyRequest,
  DeleteRequest,
  DownloadQuery,
  DuplicateRequest,
  EntryKind,
  EntryResponse,
  ExtractRequest,
  FolderSizeResponse,
  FsEntry,
  FsEntryMeta,
  isValidEntryName,
  ListResponse,
  MkdirRequest,
  MoveManyRequest,
  MoveManyResponse,
  MoveManyResult,
  MoveRequest,
  OkResponse,
  PathQuery,
  RenameRequest,
  UploadQuery,
  ZipRequest,
} from "./fs.ts";
export { HealthResponse } from "./health.ts";
export { HttpUrl, isHttpUrl } from "./http-url.ts";
export {
  ArchiveFormat,
  JobAccepted,
  JobKind,
  JobProgress,
  JobState,
  JobStatus,
  JobsResponse,
} from "./jobs.ts";
export {
  CreateTagRequest,
  FavoriteItem,
  FavoriteKind,
  FavoriteRequest,
  FavoritesResponse,
  FolderViewMode,
  FolderViewResponse,
  FolderViewSort,
  FolderViewState,
  RecentItem,
  RecentsResponse,
  RecentTouchRequest,
  RemoveFolderViewRequest,
  SetFileTagsRequest,
  SetFolderViewRequest,
  Tag,
  TagFilesResponse,
  TagsResponse,
  UpdateTagRequest,
} from "./metadata.ts";
export {
  isOfficeFilename,
  isOfficePath,
  OfficeCreateDocumentRequest,
  OfficeCreateDocumentResponse,
  OfficeMode,
  OfficeOpenRequest,
  OfficeOpenResponse,
  OfficeRuntimeConfiguration,
  OfficeSettings,
  OfficeSettingsUpdateRequest,
  OfficeStatusResponse,
  SystemOfficeResponse,
} from "./office.ts";
export * from "./processing-failures.ts";
export {
  AdminProvider,
  AdminProviderCreateRequest,
  AdminProvidersResponse,
  AdminProviderTestRequest,
  AdminProviderType,
  AdminProviderUpdateRequest,
  ProviderCapabilities,
  ProviderField,
  ProviderFieldKind,
  ProviderFieldValues,
  ProviderName,
  ProvidersResponse,
  ProviderType,
  PublicProvider,
} from "./providers.ts";
export {
  HttpOrigin,
  PUBLIC_URL_SETTINGS_KEY,
  PublicUrlSettings,
  PublicUrlUpdateRequest,
} from "./public-url.ts";
export type { Routes } from "./routes.ts";
export {
  accountTokenRoute,
  adminProviderRoute,
  adminProviderTestRoute,
  IDENTITY_HEADER,
  IDENTITY_QUERY_PARAM,
  identityScopeRoute,
  identityScopeSuggestionsRoute,
  jobCancelRoute,
  jobRoute,
  MODIFIED_AT_HEADER,
  organizeRunCancelRoute,
  organizeRunRoute,
  PUBLIC_SHARE_SUFFIXES,
  publicShareRoute,
  ROUTES,
  systemLogsRoute,
  tagFilesRoute,
  tagRoute,
} from "./routes.ts";
export {
  IdentityScopeReason,
  IdentityScopeResponse,
  IdentityScopeSuggestionsResponse,
  isCanonicalScopePath,
  MAX_MOUNT_MAPPINGS,
  MAX_SCOPE_MAPPINGS,
  MAX_SCOPE_SUGGESTIONS,
  MAX_UNMAPPED_MOUNTS,
  MountMapping,
  MountMappingsResponse,
  ScopeCanonicalPath,
  ScopeMapping,
  ScopeMappingSuggestion,
  ScopeRootName,
  SetIdentityScopeRequest,
  type SetIdentityScopeRequestInput,
  SetMountMappingsRequest,
  UnmappedMount,
} from "./scopes.ts";
export {
  ImageSearchHit,
  ImageSearchQuery,
  ImageSearchResponse,
  SearchHighlightRange,
  SearchHit,
  SearchQuery,
  SearchResponse,
  SearchSections,
  SearchSnippet,
  SearchStatusResponse,
} from "./search.ts";
export {
  ConnectionTestResponse,
  SETUP_TOKEN_HEADER,
  SetupCompleteRequest,
  SetupStatusResponse,
  SetupTestRequest,
} from "./setup.ts";
export * from "./shares.ts";
export {
  ImageEmbeddingClearJob,
  ImageEmbeddingRebuildJob,
  IndexerActionResponse,
  IndexerClearJob,
  IndexerClearRequest,
  IndexerClearResponse,
  IndexerDirectoryResponse,
  IndexerErrorSample,
  IndexerHealth,
  IndexerLastScan,
  IndexerReindexRequest,
  IndexerRootStats,
  IndexerSettingsResponse,
  IndexerSettingsSources,
  IndexerSettingsUpdateRequest,
  IndexerSettingsValue,
  IndexerStats,
  IndexerThumbnailRebuildJob,
  IndexerThumbnailsRebuildRequest,
  IndexerThumbnailsRebuildResponse,
  OcrHealth,
  OcrLastRun,
  OcrOriginal,
  OcrOriginalDeleteRequest,
  OcrOriginalDeleteResponse,
  OcrOriginalRestoreRequest,
  OcrOriginalRestoreResponse,
  OcrOriginalState,
  OcrOriginalsResponse,
  OcrRunResponse,
  OcrSettingsResponse,
  OcrSettingsSources,
  OcrSettingsUpdateRequest,
  OcrSettingsValue,
  OcrStats,
  SemanticStatus,
  SettingSource,
  SYSTEM_LOGS_MAX_LIMIT,
  SystemImageSearchResponse,
  SystemIndexerResponse,
  SystemIndexTotals,
  SystemLogEntry,
  SystemLogLevel,
  SystemLogSource,
  SystemLogSubsystem,
  SystemLogsQuery,
  SystemLogsResponse,
  SystemOcrResponse,
  SystemReembedResponse,
  SystemSearchResponse,
  SystemThumbnailsResponse,
} from "./system.ts";
export type { ThumbSize } from "./thumbs.ts";
export { THUMB_SIZES, ThumbQuery } from "./thumbs.ts";
export {
  ApiTokenAccess,
  ApiTokenExpiresInDays,
  ApiTokenSummary,
  ApiTokensResponse,
  CreateApiTokenRequest,
  CreateApiTokenResponse,
} from "./tokens.ts";
export {
  isValidPath,
  TrashConfiguration,
  TrashEntry,
  TrashListResponse,
  TrashPurgeRequest,
  TrashRestoreRequest,
  TrashRestoreResponse,
  TrashSettings,
  TrashSettingsUpdateRequest,
  TrashStatusResponse,
  TrashStrategy,
} from "./trash.ts";
