#!/bin/bash
# Create the deployment's persistent bootstrap secrets once. This script never
# overwrites an existing file, so rerunning it cannot rotate encryption keys.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ $# -gt 1 ]]; then
  echo "usage: $0 [path-to-.env]" >&2
  exit 2
fi
target="${1:-$script_dir/.env}"
if [[ -e $target ]]; then
  echo "refusing to overwrite existing $target" >&2
  exit 1
fi
parent="$(dirname "$target")"
if [[ ! -d $parent ]]; then
  echo "parent directory does not exist: $parent" >&2
  exit 1
fi

umask 077
temp="$(mktemp "$parent/.fdrive-env.XXXXXX")"
trap 'rm -f "$temp"' EXIT
master_key="$(openssl rand -base64 32)"
database_password="$(openssl rand -hex 32)"
cat >"$temp" <<EOF
# Generated by init-env.sh. Keep this file private and do not rotate either
# value after users have signed in: FDRIVE_MASTER_KEY encrypts stored credentials.
FDRIVE_MASTER_KEY=$master_key
POSTGRES_PASSWORD=$database_password

# SFTPGO_URL=
EOF
chmod 600 "$temp"
if ! ln "$temp" "$target" 2>/dev/null; then
  echo "refusing to overwrite existing $target" >&2
  exit 1
fi
rm -f "$temp"
trap - EXIT
echo "created $target"
