import { randomBytes } from "node:crypto";
import { writeFile } from "node:fs/promises";

export type OfficeProduct = "onlyoffice" | "collabora";

export function officeProduct(value: string | undefined): OfficeProduct {
  if (value === "onlyoffice" || value === "collabora") return value;
  throw new Error("Usage: setup.ts onlyoffice|collabora");
}

export function devEnvironment(product: OfficeProduct, secret: string): string {
  if (!/^[a-f0-9]{64}$/.test(secret)) throw new Error("Expected a 32-byte hexadecimal JWT secret");
  const port = product === "onlyoffice" ? 58090 : 58091;
  return [
    "# Generated by tools/office/setup.ts. Private local configuration.",
    `FDRIVE_OFFICE_PRODUCT=${product}`,
    `FDRIVE_OFFICE_URL=http://localhost:${port}`,
    `FDRIVE_OFFICE_PUBLIC_URL=http://localhost:${port}`,
    "FDRIVE_WOPI_URL=http://host.docker.internal:3001/wopi",
    "FDRIVE_PUBLIC_URL=http://localhost:3002",
    "FDRIVE_OFFICE_MAX_BYTES=104857600",
    `ONLYOFFICE_JWT_SECRET=${secret}`,
    "",
  ].join("\n");
}

export async function createDevEnvironment(path: string, product: OfficeProduct): Promise<boolean> {
  const contents = devEnvironment(product, randomBytes(32).toString("hex"));
  try {
    await writeFile(path, contents, { flag: "wx", mode: 0o600 });
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "EEXIST") return false;
    throw error;
  }
}
