import { sql } from "drizzle-orm";
import {
  bigint,
  bigserial,
  customType,
  index,
  integer,
  pgSchema,
  smallint,
  smallserial,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { vector } from "../vector.js";

/**
 * Postgres tsvector, generated by the `chunks.tsv` column. Never written to
 * directly, so only the read side (a plain string) matters here.
 */
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

export const idxSchema = pgSchema("idx");

export const roots = idxSchema.table("roots", {
  id: smallserial("id").primaryKey(),
  name: text("name").notNull().unique(),
});

export const files = idxSchema.table(
  "files",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    path: text("path").notNull(),
    name: text("name").notNull(),
    ext: text("ext").notNull().default(""),
    size: bigint("size", { mode: "number" }).notNull(),
    mtimeNs: bigint("mtime_ns", { mode: "bigint" }).notNull(),
    sha256: text("sha256"),
    mime: text("mime"),
    textStatus: text("text_status").notNull().default("pending"),
    textChars: integer("text_chars").notNull().default(0),
    error: text("error"),
    firstSeen: timestamp("first_seen", { withTimezone: true }).defaultNow(),
    lastSeen: timestamp("last_seen", { withTimezone: true }).defaultNow(),
    indexedAt: timestamp("indexed_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("files_root_id_path_unique").on(table.rootId, table.path),
    index("files_sha256_idx").on(table.sha256),
    index("files_mtime_ns_idx").on(table.mtimeNs),
    index("files_text_status_idx").on(table.textStatus),
    index("files_name_trgm_idx").using("gin", table.name.op("gin_trgm_ops")),
    index("files_path_trgm_idx").using("gin", table.path.op("gin_trgm_ops")),
  ],
);

export const chunks = idxSchema.table(
  "chunks",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    fileId: bigint("file_id", { mode: "number" })
      .notNull()
      .references(() => files.id, { onDelete: "cascade" }),
    idx: integer("idx").notNull(),
    text: text("text").notNull(),
    tsv: tsvector("tsv").generatedAlwaysAs(sql`to_tsvector('simple', "text")`),
    embedding: vector("embedding", { dimensions: 384 }),
  },
  (table) => [
    index("chunks_file_id_idx").on(table.fileId),
    index("chunks_tsv_idx").using("gin", table.tsv),
    index("chunks_embedding_hnsw_idx").using("hnsw", table.embedding.op("vector_cosine_ops")),
  ],
);

export const scans = idxSchema.table(
  "scans",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    filesSeen: integer("files_seen").notNull().default(0),
    filesChanged: integer("files_changed").notNull().default(0),
    filesDeleted: integer("files_deleted").notNull().default(0),
    errors: integer("errors").notNull().default(0),
  },
  // The indexer reads the latest scan per root on every status poll
  // (`root_id = ? order by started_at desc limit 1`), which without this
  // index scans the whole history table.
  (table) => [index("scans_root_id_started_at_idx").on(table.rootId, table.startedAt.desc())],
);

export const moves = idxSchema.table(
  "moves",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).defaultNow(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    src: text("src"),
    dst: text("dst"),
    actor: text("actor"),
  },
  // `recentMoves` restricts every scope clause with `root_id = ?`, so the
  // scope filter has no access path without this index.
  (table) => [index("moves_root_id_idx").on(table.rootId)],
);

export const events = idxSchema.table(
  "events",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).defaultNow(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    kind: text("kind").notNull(),
    path: text("path").notNull(),
    targetPath: text("target_path"),
  },
  (table) => [index("events_at_idx").on(table.at)],
);

export const schemaVersion = idxSchema.table("schema_version", {
  version: integer("version").primaryKey(),
});

/** Current unresolved failures plus bounded resolved history, written by processing workers. */
export const processingFailures = idxSchema.table(
  "processing_failures",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id, { onDelete: "cascade" }),
    path: text("path").notNull(),
    feature: text("feature").notNull(),
    code: text("code").notNull(),
    message: text("message").notNull(),
    operationId: text("operation_id").notNull(),
    attempts: integer("attempts").notNull().default(1),
    firstFailedAt: timestamp("first_failed_at", { withTimezone: true }).notNull().defaultNow(),
    lastFailedAt: timestamp("last_failed_at", { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (table) => [
    unique("processing_failures_root_path_feature_unique").on(
      table.rootId,
      table.path,
      table.feature,
    ),
    index("processing_failures_feature_resolved_id_idx").on(
      table.feature,
      table.resolvedAt,
      table.id.desc(),
    ),
    index("processing_failures_resolved_idx").on(table.resolvedAt),
  ],
);

export const ocrLog = idxSchema.table(
  "ocr_log",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    path: text("path").notNull(),
    size: bigint("size", { mode: "number" }).notNull(),
    mtimeNs: bigint("mtime_ns", { mode: "bigint" }).notNull(),
    status: text("status").notNull(),
    detail: text("detail"),
    at: timestamp("at", { withTimezone: true }).defaultNow(),
  },
  // The system event feed reads only failures, newest first
  // (`status in ('failed','timeout') [and at < ?] order by at desc nulls last`).
  // `status` leads because it is the equality side; `at` follows in the
  // order the feed asks for so the index serves the range and the sort.
  (table) => [
    unique("ocr_log_root_id_path_size_mtime_ns_unique").on(
      table.rootId,
      table.path,
      table.size,
      table.mtimeNs,
    ),
    index("ocr_log_status_at_idx").on(table.status, table.at.desc().nullsLast()),
  ],
);

export const ocrRuns = idxSchema.table("ocr_runs", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  seen: integer("seen").notNull().default(0),
  ocred: integer("ocred").notNull().default(0),
  skipped: integer("skipped").notNull().default(0),
  failed: integer("failed").notNull().default(0),
});
