import { sql } from "drizzle-orm";
import {
  bigint,
  bigserial,
  customType,
  index,
  integer,
  pgSchema,
  smallint,
  smallserial,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { vector } from "../vector.js";

/**
 * Postgres tsvector, generated by the `chunks.tsv` column. Never written to
 * directly, so only the read side (a plain string) matters here.
 */
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

export const idxSchema = pgSchema("idx");

export const roots = idxSchema.table("roots", {
  id: smallserial("id").primaryKey(),
  name: text("name").notNull().unique(),
});

export const files = idxSchema.table(
  "files",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    path: text("path").notNull(),
    name: text("name").notNull(),
    ext: text("ext").notNull().default(""),
    size: bigint("size", { mode: "number" }).notNull(),
    mtimeNs: bigint("mtime_ns", { mode: "bigint" }).notNull(),
    sha256: text("sha256"),
    mime: text("mime"),
    textStatus: text("text_status").notNull().default("pending"),
    textChars: integer("text_chars").notNull().default(0),
    error: text("error"),
    firstSeen: timestamp("first_seen", { withTimezone: true }).defaultNow(),
    lastSeen: timestamp("last_seen", { withTimezone: true }).defaultNow(),
    indexedAt: timestamp("indexed_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    unique("files_root_id_path_unique").on(table.rootId, table.path),
    index("files_sha256_idx").on(table.sha256),
    index("files_mtime_ns_idx").on(table.mtimeNs),
    index("files_text_status_idx").on(table.textStatus),
  ],
);

export const chunks = idxSchema.table(
  "chunks",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    fileId: bigint("file_id", { mode: "number" })
      .notNull()
      .references(() => files.id, { onDelete: "cascade" }),
    idx: integer("idx").notNull(),
    text: text("text").notNull(),
    tsv: tsvector("tsv").generatedAlwaysAs(sql`to_tsvector('simple', "text")`),
    embedding: vector("embedding", { dimensions: 384 }),
  },
  (table) => [index("chunks_file_id_idx").on(table.fileId)],
);

export const scans = idxSchema.table("scans", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  rootId: smallint("root_id")
    .notNull()
    .references(() => roots.id),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  filesSeen: integer("files_seen").notNull().default(0),
  filesChanged: integer("files_changed").notNull().default(0),
  filesDeleted: integer("files_deleted").notNull().default(0),
  errors: integer("errors").notNull().default(0),
});

export const moves = idxSchema.table("moves", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  at: timestamp("at", { withTimezone: true }).defaultNow(),
  rootId: smallint("root_id")
    .notNull()
    .references(() => roots.id),
  src: text("src"),
  dst: text("dst"),
  actor: text("actor"),
});

export const events = idxSchema.table(
  "events",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    at: timestamp("at", { withTimezone: true }).defaultNow(),
    rootId: smallint("root_id")
      .notNull()
      .references(() => roots.id),
    kind: text("kind").notNull(),
    path: text("path").notNull(),
    targetPath: text("target_path"),
  },
  (table) => [index("events_at_idx").on(table.at)],
);

export const schemaVersion = idxSchema.table("schema_version", {
  version: integer("version").primaryKey(),
});
